### ISSUE TITLE
Texture missing in GTFO and some textures not connect with other block

### ISSUE THREAD

**Issue by EtaCarina** [ULSTICK/GregTechRefreshed#18]
①Texture missing in GTFO
![2024-05-30_09 55 17](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/5704f179-b611-43ba-be9c-b7810dab9f4d)
![2024-05-30_09 55 21](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/a87bac2c-0493-4de4-bc72-5739605fac66)
![2024-05-30_09 55 24](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/d69d74fc-f42d-466e-a1ee-b5858e98d987)
②Some textures not connect with other block, even add Optifine and CTM
![2024-05-30_09 53 11](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/20b222b9-e181-4609-908d-efbc4ad475f7)
![2024-05-30_09 54 41](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/32d72073-248a-495f-b733-ee5a13bcba6a)
![2024-05-30_09 54 46](https://github.com/ULSTICK/GregTechRefreshed/assets/20508876/5b16ade2-3590-4285-a924-82ead3b3105f)

Use the latest version of pack(1.12)

**Comment by BlueHero233** [comment]
Gregtech Food Option is not Gregtech Modern, if those textures are missing thats a problem of their part

Also 1.12 version doesnt have blockstate/tileentity functions so hatches, buses, mufflers and controllers dont exactly connect to the rest of the casings like in 1.20, its a code issue not a texture issue unfortunately
