### ISSUE TITLE
Flud cells don't show fluid texture

### ISSUE THREAD

**Issue by Ignus3** [ULSTICK/GregTechRefreshed#21]
One of the really nice things about the base greg modern fluid cells is that you can tell by looking at them what's inside them. I LOVE this pack, but I'd love for the cells to have that feature as well.

**Comment by Ignus3** [comment]
After poking around, I can see that there is code very similar to base greg for this, but it's not working.. Hmm. Maybe I'll try and reach out and see if it's something I can help troubleshoot

**Comment by Ignus3** [comment]
Best I can think of is that the base gtceu is using a flat file with a single rectangle and then I think coloring it, where here it looks like there's 4 rectangles and an mcmeta file to create an animation. Might be that the animation part is breaking it? Not sure.

**Comment by ULSTICK** [comment]
I have found a way to fix it by changing the item model. the model from the original mod puts the base in front of the fluid part.
Will be fixed in the next update

**Comment by Ignus3** [comment]
Thanks! Glad to hear it, And thank you again for all your amazing work on this mod
