### ISSUE TITLE
Hot ingot textures

### ISSUE THREAD

**Issue by DadamaldaDad** [ULSTICK/GregTechRefreshed#22]
All hot ingots with this shape have dark pixels where they shouldn't be, it looks bad and inconsistent.
![Snímek obrazovky 2024-07-14 204206](https://github.com/user-attachments/assets/0081d631-c1f6-4992-9b73-1469c59e5362)
![Snímek obrazovky 2024-07-14 204234](https://github.com/user-attachments/assets/2be5a775-4888-44f1-8816-f56bfaf60a02)
![Snímek obrazovky 2024-07-14 204312](https://github.com/user-attachments/assets/95537581-e9bf-4be7-aaa1-390b358972f7)
![Snímek obrazovky 2024-07-14 204334](https://github.com/user-attachments/assets/79d89b2d-713e-4f3a-9aa4-8a9f44a34cd5)

**Comment by ULSTICK** [comment]
All ingots will have different hot overlays

**Comment by ULSTICK** [comment]
Fixed
