### ISSUE TITLE
Won't you add UHV+ textures?

### ISSUE THREAD

**Issue by xingluo01** [ULSTICK/GregTechRefreshed#5]
I don't know if such a question should be asked, I used machine translation, the tone may not be very good.

**Comment by ULSTICK** [comment]
I assume you're here for the 1.12 one? Since I'm following the GTCEu Modern and UHV+ items are not yet implemented in it, I will be focusing on the Items available first!
I will eventually make it tho, just not on priority!

**Comment by xingluo01** [comment]
Is 1.20.1

**Comment by ULSTICK** [comment]
oh my apologies then, Yeah it will be worked on after some updates
